/* AUTO-GENERATED by scripts/generate-stats.ts — do not edit by hand. */

export interface LandingStat {
  big: string;
  sml: string;
  sub: string;
}

export const STATS_GENERATED_AT = "2026-05-16T16:33:18.866Z";

export const LANDING_STATS: LandingStat[] = [
  {
    big: "18",
    sml: "GitHub stars",
    sub: "across the w3-kit org",
  },
  {
    big: "37",
    sml: "npm downloads / week",
    sub: "across @w3-kit/*",
  },
  {
    big: "27",
    sml: "components shipped",
    sub: "typed, themed, ready",
  },
  {
    big: "14",
    sml: "chains supported",
    sub: "EVM + Solana",
  },
];
