// AUTO-GENERATED by scripts/generate-learn-registry.ts — do not edit manually

import accessibilityDoc from "@learn/docs/accessibility.md?raw";
import cliCommandsDoc from "@learn/docs/cli-commands.md?raw";
import cliDoc from "@learn/docs/cli.md?raw";
import componentsApiDoc from "@learn/docs/components-api.md?raw";
import componentsDoc from "@learn/docs/components.md?raw";
import configurationDoc from "@learn/docs/configuration.md?raw";
import contractsDoc from "@learn/docs/contracts.md?raw";
import designTokensDoc from "@learn/docs/design-tokens.md?raw";
import hooksUtilitiesDoc from "@learn/docs/hooks-utilities.md?raw";
import installationDoc from "@learn/docs/installation.md?raw";
import introductionDoc from "@learn/docs/introduction.md?raw";
import projectStructureDoc from "@learn/docs/project-structure.md?raw";
import registryDoc from "@learn/docs/registry.md?raw";
import themingDoc from "@learn/docs/theming.md?raw";
import uiLibraryDoc from "@learn/docs/ui-library.md?raw";

export const docContentMap: Record<string, string> = {
  "accessibility": accessibilityDoc,
  "cli-commands": cliCommandsDoc,
  "cli": cliDoc,
  "components-api": componentsApiDoc,
  "components": componentsDoc,
  "configuration": configurationDoc,
  "contracts": contractsDoc,
  "design-tokens": designTokensDoc,
  "hooks-utilities": hooksUtilitiesDoc,
  "installation": installationDoc,
  "introduction": introductionDoc,
  "project-structure": projectStructureDoc,
  "registry": registryDoc,
  "theming": themingDoc,
  "ui-library": uiLibraryDoc,
};
