// AUTO-GENERATED by scripts/generate-learn-registry.ts — do not edit manually

export interface DocNavItem {
  label: string;
  slug: string;
  type: "markdown" | "guide" | "recipe";
}

export interface DocNavSection {
  title: string;
  items: DocNavItem[];
}

export const docsNavSections: DocNavSection[] = [
  {
    title: "Getting Started",
    items: [
      { label: "Configuration", slug: "configuration", type: "markdown" },
      { label: "Installation", slug: "installation", type: "markdown" },
      { label: "Introduction", slug: "introduction", type: "markdown" },
      { label: "Project Structure", slug: "project-structure", type: "markdown" },
    ],
  },
  {
    title: "Core Concepts",
    items: [
      { label: "Accessibility", slug: "accessibility", type: "markdown" },
      { label: "Components", slug: "components", type: "markdown" },
      { label: "Design Tokens", slug: "design-tokens", type: "markdown" },
      { label: "Theming", slug: "theming", type: "markdown" },
    ],
  },
  {
    title: "Ecosystem",
    items: [
      { label: "Cli", slug: "cli", type: "markdown" },
      { label: "Contracts", slug: "contracts", type: "markdown" },
      { label: "Registry", slug: "registry", type: "markdown" },
      { label: "Ui Library", slug: "ui-library", type: "markdown" },
    ],
  },
  {
    title: "API Reference",
    items: [
      { label: "Cli Commands", slug: "cli-commands", type: "markdown" },
      { label: "Components Api", slug: "components-api", type: "markdown" },
      { label: "Hooks Utilities", slug: "hooks-utilities", type: "markdown" },
    ],
  },
  {
    title: "Guides: Cheatsheets",
    items: [
      { label: "Solidity vs Rust: Syntax Comparison", slug: "solidity-vs-rust", type: "guide" },
    ],
  },
  {
    title: "Guides: Concepts",
    items: [
      { label: "Accounts Model — EVM vs Solana, Side-by-Side", slug: "accounts-model", type: "guide" },
      { label: "How Transactions Work", slug: "how-transactions-work", type: "guide" },
      { label: "Public vs Private Keys", slug: "public-vs-private-keys", type: "guide" },
      { label: "What Are Smart Contracts?", slug: "what-are-smart-contracts", type: "guide" },
      { label: "What Is a Wallet?", slug: "what-is-a-wallet", type: "guide" },
    ],
  },
  {
    title: "Guides: Evm",
    items: [
      { label: "Gas Explained — EVM Fee Mechanics From First Principles", slug: "gas-explained", type: "guide" },
    ],
  },
  {
    title: "Guides: Glossary",
    items: [
      { label: "Web3 Glossary", slug: "glossary", type: "guide" },
    ],
  },
  {
    title: "Guides: Security",
    items: [
      { label: "Top 10 Smart Contract Vulnerabilities — EVM & Solana", slug: "top-10-vulnerabilities", type: "guide" },
    ],
  },
  {
    title: "Guides: Solana",
    items: [
      { label: "PDAs Explained — Program Derived Addresses From First Principles", slug: "pdas-explained", type: "guide" },
    ],
  },
  {
    title: "Recipes: Wallet",
    items: [
      { label: "Connect Wallet", slug: "connect-wallet", type: "recipe" },
      { label: "Disconnect Wallet", slug: "disconnect-wallet", type: "recipe" },
      { label: "Sign Message", slug: "sign-message", type: "recipe" },
      { label: "Switch Network", slug: "switch-network", type: "recipe" },
    ],
  },
  {
    title: "Recipes: Tokens",
    items: [
      { label: "Approve Spending", slug: "approve-spending", type: "recipe" },
      { label: "Create Token", slug: "create-token", type: "recipe" },
      { label: "Fetch Metadata", slug: "fetch-metadata", type: "recipe" },
      { label: "Get Balance", slug: "get-balance", type: "recipe" },
      { label: "Transfer Tokens", slug: "transfer-tokens", type: "recipe" },
      { label: "Watch Transfers", slug: "watch-transfers", type: "recipe" },
    ],
  },
  {
    title: "Recipes: Nfts",
    items: [
      { label: "Buy Nft", slug: "buy-nft", type: "recipe" },
      { label: "Display Nft Metadata", slug: "display-nft-metadata", type: "recipe" },
      { label: "Fetch Nft Collection", slug: "fetch-nft-collection", type: "recipe" },
      { label: "Mint Nft", slug: "mint-nft", type: "recipe" },
      { label: "Onchain Svg Nft", slug: "onchain-svg-nft", type: "recipe" },
    ],
  },
  {
    title: "Recipes: Defi",
    items: [
      { label: "Claim Rewards", slug: "claim-rewards", type: "recipe" },
      { label: "Provide Liquidity", slug: "provide-liquidity", type: "recipe" },
      { label: "Stake Tokens", slug: "stake-tokens", type: "recipe" },
      { label: "Swap Tokens", slug: "swap-tokens", type: "recipe" },
    ],
  },
  {
    title: "Recipes: Utils",
    items: [
      { label: "Estimate Fees", slug: "estimate-fees", type: "recipe" },
      { label: "Resolve Address", slug: "resolve-address", type: "recipe" },
    ],
  },
];

/** Flat ordered list of all nav items (useful for prev/next navigation) */
export const allDocNavItems = docsNavSections.flatMap((s) =>
  s.items.map((item) => ({ ...item, section: s.title })),
);
