// AUTO-GENERATED by scripts/generate-learn-registry.ts — do not edit manually
import type { GuideMeta } from "./types";

import solidityVsRustContent from "@learn/guides/cheatsheets/solidity-vs-rust.md?raw";
import accountsModelContent from "@learn/guides/concepts/accounts-model.md?raw";
import howTransactionsWorkContent from "@learn/guides/concepts/how-transactions-work.md?raw";
import publicVsPrivateKeysContent from "@learn/guides/concepts/public-vs-private-keys.md?raw";
import whatAreSmartContractsContent from "@learn/guides/concepts/what-are-smart-contracts.md?raw";
import whatIsAWalletContent from "@learn/guides/concepts/what-is-a-wallet.md?raw";
import gasExplainedContent from "@learn/guides/evm/gas-explained.md?raw";
import glossaryContent from "@learn/guides/glossary/glossary.md?raw";
import top10VulnerabilitiesContent from "@learn/guides/security/top-10-vulnerabilities.md?raw";
import pdasExplainedContent from "@learn/guides/solana/pdas-explained.md?raw";

export const guideRegistry: GuideMeta[] = [
  {
    id: "solidity-vs-rust",
    title: "Solidity vs Rust: Syntax Comparison",
    description: "Learn about solidity vs rust: syntax comparison",
    category: "cheatsheets" as GuideMeta["category"],
    slug: "solidity-vs-rust",
    content: solidityVsRustContent,
    author: "Raad05",
  },
  {
    id: "accounts-model",
    title: "Accounts Model — EVM vs Solana, Side-by-Side",
    description: "Learn about accounts model — evm vs solana, side-by-side",
    category: "concepts" as GuideMeta["category"],
    slug: "accounts-model",
    content: accountsModelContent,
    author: "PetarStoev02",
  },
  {
    id: "how-transactions-work",
    title: "How Transactions Work",
    description: "Learn about how transactions work",
    category: "concepts" as GuideMeta["category"],
    slug: "how-transactions-work",
    content: howTransactionsWorkContent,
    author: "PetarStoev02",
  },
  {
    id: "public-vs-private-keys",
    title: "Public vs Private Keys",
    description: "Learn about public vs private keys",
    category: "concepts" as GuideMeta["category"],
    slug: "public-vs-private-keys",
    content: publicVsPrivateKeysContent,
    author: "PetarStoev02",
  },
  {
    id: "what-are-smart-contracts",
    title: "What Are Smart Contracts?",
    description: "Learn about what are smart contracts?",
    category: "concepts" as GuideMeta["category"],
    slug: "what-are-smart-contracts",
    content: whatAreSmartContractsContent,
    author: "PetarStoev02",
  },
  {
    id: "what-is-a-wallet",
    title: "What Is a Wallet?",
    description: "Learn about what is a wallet?",
    category: "concepts" as GuideMeta["category"],
    slug: "what-is-a-wallet",
    content: whatIsAWalletContent,
    author: "PetarStoev02",
  },
  {
    id: "gas-explained",
    title: "Gas Explained — EVM Fee Mechanics From First Principles",
    description: "Learn about gas explained — evm fee mechanics from first principles",
    category: "evm" as GuideMeta["category"],
    slug: "gas-explained",
    content: gasExplainedContent,
    author: "PetarStoev02",
  },
  {
    id: "glossary",
    title: "Web3 Glossary",
    description: "Learn about web3 glossary",
    category: "glossary" as GuideMeta["category"],
    slug: "glossary",
    content: glossaryContent,
    author: "PetarStoev02",
  },
  {
    id: "top-10-vulnerabilities",
    title: "Top 10 Smart Contract Vulnerabilities — EVM & Solana",
    description: "Learn about top 10 smart contract vulnerabilities — evm & solana",
    category: "security" as GuideMeta["category"],
    slug: "top-10-vulnerabilities",
    content: top10VulnerabilitiesContent,
    author: "PetarStoev02",
  },
  {
    id: "pdas-explained",
    title: "PDAs Explained — Program Derived Addresses From First Principles",
    description: "Learn about pdas explained — program derived addresses from first principles",
    category: "solana" as GuideMeta["category"],
    slug: "pdas-explained",
    content: pdasExplainedContent,
    author: "PetarStoev02",
  },
];
