import type { ComponentMeta } from "./types";

const GITHUB_BASE = "https://github.com/w3-kit/w3-kit/tree/main/ui/components";

export const componentRegistry: ComponentMeta[] = [
  // ── Wallet ──────────────────────────────────────────────
  {
    id: "connect-wallet",
    name: "Connect Wallet",
    description:
      "Wallet picker with multi-wallet support, connected state, chain switching, and disconnect. Pure UI — bring your own wallet logic.",
    category: "wallet",
    tags: ["metamask", "walletconnect", "coinbase", "phantom", "wagmi"],
    hasPreview: true,
    importPath: "w3-kit/connect-wallet",
    sourceUrl: `${GITHUB_BASE}/connect-wallet`,
    props: [
      { name: "wallets", type: "WalletOption[]", required: true, description: "List of wallets to display (id, name, icon, ecosystem)" },
      { name: "connectedAccount", type: "ConnectedAccount | null", required: false, description: "Connected account data. null = show wallet picker" },
      { name: "onConnect", type: "(walletId: string) => void", required: true, description: "Called when user selects a wallet to connect" },
      { name: "onDisconnect", type: "() => void", required: false, description: "Called when user clicks disconnect" },
      { name: "chains", type: "Chain[]", required: false, description: "Supported chains for the chain switcher" },
      { name: "activeChain", type: "Chain", required: false, description: "Currently active chain" },
      { name: "onChainSwitch", type: "(chainId: number) => void", required: false, description: "Called when user switches chain" },
      { name: "recentWalletId", type: "string", required: false, description: "ID of the most recently used wallet (shown highlighted)" },
      { name: "variant", type: '"default" | "compact"', required: false, default: '"default"', description: "default = full picker, compact = button that opens picker" },
      { name: "loading", type: "boolean", required: false, default: "false", description: "Show loading state on the selected wallet" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "network-switcher",
    name: "Network Switcher",
    description: "Clean list-based chain selector with testnet toggle, search, and per-chain loading state. Parent controls active chain.",
    category: "wallet",
    tags: ["chain", "network", "switch", "ethereum", "l2"],
    hasPreview: true,
    importPath: "w3-kit/network-switcher",
    sourceUrl: `${GITHUB_BASE}/network-switcher`,
    props: [
      { name: "networks", type: "Network[]", required: true, description: "All networks (use .testnet: true for testnets)" },
      { name: "activeChainId", type: "number", required: false, description: "Currently active chain ID (parent-controlled)" },
      { name: "onSwitch", type: "(chainId: number) => void | Promise<void>", required: true, description: "Called when user selects a network" },
      { name: "searchable", type: "boolean", required: false, default: "false", description: "Show search input (useful for large network lists)" },
      { name: "showTestnetToggle", type: "boolean", required: false, description: "Show testnet toggle (auto-detected from .testnet fields)" },
      { name: "switchingTo", type: "number", required: false, description: "Chain ID being switched to (shows loading spinner)" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "wallet-balance",
    name: "Wallet Balance",
    description:
      "Portfolio overview with total value, weighted 24h change, allocation bar with cross-hover, and token list sorted by value.",
    category: "wallet",
    tags: ["balance", "portfolio", "tokens", "allocation"],
    hasPreview: true,
    importPath: "w3-kit/wallet-balance",
    sourceUrl: `${GITHUB_BASE}/wallet-balance`,
    props: [
      { name: "tokens", type: "Token[]", required: true, description: "Tokens with balance, price, optional logo/color/priceChange24h" },
      { name: "onTokenClick", type: "(token: Token) => void", required: false, description: "Called when user clicks a token row" },
      { name: "onSend", type: "(token: Token) => void", required: false, description: "Called when user clicks send on a token" },
      { name: "onSwap", type: "(token: Token) => void", required: false, description: "Called when user clicks swap on a token" },
      { name: "onRefresh", type: "() => void | Promise<void>", required: false, description: "Refresh callback with loading spinner" },
      { name: "showAllocation", type: "boolean", required: false, default: "true", description: "Show allocation bar above token list" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "address-book",
    name: "Address Book",
    description: "Manage saved addresses with ENS name support, notes, and CRUD operations.",
    category: "wallet",
    tags: ["address", "ens", "contacts"],
    hasPreview: false,
    importPath: "w3-kit/address-book",
    sourceUrl: `${GITHUB_BASE}/address-book`,
    props: [
      { name: "entries", type: "AddressEntry[]", required: true, description: "List of saved address entries" },
      { name: "onAdd", type: "(entry: Omit<AddressEntry, 'id'>) => void", required: false, description: "Callback when adding a new entry" },
      { name: "onEdit", type: "(entry: AddressEntry) => void", required: false, description: "Callback when editing an entry" },
      { name: "onDelete", type: "(id: string) => void", required: false, description: "Callback when deleting an entry" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "multisig-wallet",
    name: "Multisig Wallet",
    description:
      "Multi-signature wallet with transaction list, approval progress bars, signer avatars, and tab filtering. Parent owns all state.",
    category: "wallet",
    tags: ["multisig", "gnosis", "safe", "approval"],
    hasPreview: true,
    importPath: "w3-kit/multisig-wallet",
    sourceUrl: `${GITHUB_BASE}/multisig-wallet`,
    props: [
      { name: "walletAddress", type: "string", required: true, description: "The multisig wallet address" },
      { name: "signers", type: "Signer[]", required: true, description: "List of wallet signers" },
      { name: "transactions", type: "Transaction[]", required: true, description: "Transaction list (parent-owned)" },
      { name: "requiredApprovals", type: "number", required: true, description: "Approval threshold" },
      { name: "onApprove", type: "(txId: string) => void", required: false, description: "Called when user approves a transaction" },
      { name: "onReject", type: "(txId: string) => void", required: false, description: "Called when user rejects a transaction" },
      { name: "onPropose", type: "() => void", required: false, description: "Called when user clicks propose (parent handles form)" },
      { name: "approvingId", type: "string", required: false, description: "Transaction ID being approved (shows loading)" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },

  // ── DeFi ────────────────────────────────────────────────
  {
    id: "token-swap",
    name: "Token Swap",
    description: "Clean swap widget with token selectors, flip button, exchange rate display, and inline dropdowns. Pure UI, parent provides rate.",
    category: "defi",
    tags: ["swap", "dex", "exchange", "uniswap"],
    hasPreview: true,
    importPath: "w3-kit/token-swap",
    sourceUrl: `${GITHUB_BASE}/token-swap`,
    props: [
      { name: "tokens", type: "SwapToken[]", required: true, description: "Available tokens for selection" },
      { name: "fromToken", type: "SwapToken", required: false, description: "Currently selected from token" },
      { name: "toToken", type: "SwapToken", required: false, description: "Currently selected to token" },
      { name: "onSwap", type: "(params: { from, to, amount }) => void | Promise<void>", required: true, description: "Called when user clicks swap" },
      { name: "onFromTokenChange", type: "(token: SwapToken) => void", required: false, description: "Called when user changes from token" },
      { name: "onToTokenChange", type: "(token: SwapToken) => void", required: false, description: "Called when user changes to token" },
      { name: "exchangeRate", type: "number", required: false, description: "How many toTokens per 1 fromToken" },
      { name: "slippage", type: "number", required: false, description: "Slippage tolerance percentage" },
      { name: "loading", type: "boolean", required: false, default: "false", description: "Loading state on swap button" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "staking-interface",
    name: "Staking Interface",
    description:
      "Props-driven staking pool list with expandable details, stake/unstake toggle, per-pool userStaked amount, and APR display. No injected CSS.",
    category: "defi",
    tags: ["staking", "yield", "apr", "pool"],
    hasPreview: true,
    importPath: "w3-kit/staking-interface",
    sourceUrl: `${GITHUB_BASE}/staking-interface`,
    props: [
      { name: "pools", type: "StakingPool[]", required: true, description: "Available staking pools (id, name, token, icon, apr, lockPeriod, totalStaked, userStaked, minStake)" },
      { name: "onStake", type: "(poolId: string, amount: string) => void", required: false, description: "Called when user stakes into a pool" },
      { name: "onUnstake", type: "(poolId: string, amount: string) => void", required: false, description: "Called when user unstakes from a pool" },
      { name: "stakingPoolId", type: "string", required: false, description: "Pool ID currently being staked to (shows loading spinner)" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "bridge",
    name: "Bridge Widget",
    description: "Cross-chain bridge UI with from/to network selectors, token picker, amount input, and swap button. Pure UI — parent controls all state via props.",
    category: "defi",
    tags: ["bridge", "cross-chain", "transfer", "l2"],
    hasPreview: true,
    importPath: "w3-kit/bridge",
    sourceUrl: `${GITHUB_BASE}/bridge`,
    props: [
      { name: "networks", type: "BridgeNetwork[]", required: true, description: "Available networks (id, name, icon?, color?)" },
      { name: "tokens", type: "BridgeToken[]", required: true, description: "Available tokens (symbol, name, icon?, balance?)" },
      { name: "fromNetwork", type: "BridgeNetwork", required: false, description: "Currently selected source network" },
      { name: "toNetwork", type: "BridgeNetwork", required: false, description: "Currently selected destination network" },
      { name: "selectedToken", type: "BridgeToken", required: false, description: "Currently selected token" },
      { name: "onBridge", type: "(params: { from, to, token, amount }) => void", required: false, description: "Called when user clicks the bridge button" },
      { name: "onFromNetworkChange", type: "(network: BridgeNetwork) => void", required: false, description: "Called when source network changes" },
      { name: "onToNetworkChange", type: "(network: BridgeNetwork) => void", required: false, description: "Called when destination network changes" },
      { name: "onTokenChange", type: "(token: BridgeToken) => void", required: false, description: "Called when token changes" },
      { name: "loading", type: "boolean", required: false, default: "false", description: "Show loading state on the bridge button" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "defi-position-manager",
    name: "DeFi Position Manager",
    description:
      "Clean position list with health factor bar, APY, and risk badges for open DeFi positions.",
    category: "defi",
    tags: ["position", "health", "apy", "risk"],
    hasPreview: true,
    importPath: "w3-kit/defi-position-manager",
    sourceUrl: `${GITHUB_BASE}/defi-position-manager`,
    props: [
      { name: "positions", type: "Position[]", required: true, description: "Array of DeFi positions to display" },
      { name: "onPositionClick", type: "(position: Position) => void", required: false, description: "Callback when a position row is clicked" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "flash-loan-executor",
    name: "Flash Loan Executor",
    description:
      "Props-driven flash loan UI with protocol selector, token dropdown, fee calculation, and execute button. Supports controlled and uncontrolled selection.",
    category: "defi",
    tags: ["flash-loan", "aave", "dydx", "arbitrage"],
    hasPreview: true,
    importPath: "w3-kit/flash-loan-executor",
    sourceUrl: `${GITHUB_BASE}/flash-loan-executor`,
    props: [
      { name: "protocols", type: "FlashLoanProtocol[]", required: true, description: "Available protocols (id, name, icon, fee)" },
      { name: "tokens", type: "FlashLoanToken[]", required: true, description: "Available tokens (symbol, name, icon, maxAmount)" },
      { name: "selectedProtocol", type: "FlashLoanProtocol", required: false, description: "Controlled selected protocol (uncontrolled if omitted)" },
      { name: "selectedToken", type: "FlashLoanToken", required: false, description: "Controlled selected token (uncontrolled if omitted)" },
      { name: "onExecute", type: "(params: { protocol, token, amount }) => void", required: false, description: "Called when user clicks execute with valid amount" },
      { name: "onProtocolChange", type: "(protocol: FlashLoanProtocol) => void", required: false, description: "Called when user switches protocol" },
      { name: "onTokenChange", type: "(token: FlashLoanToken) => void", required: false, description: "Called when user switches token" },
      { name: "loading", type: "boolean", required: false, default: "false", description: "Show loading spinner on execute button" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "limit-order-manager",
    name: "Limit Order Manager",
    description:
      "Clean order list with tab filtering (Active / Filled / All), buy/sell type badges, status indicators, and cancel with loading state. Parent owns all state.",
    category: "defi",
    tags: ["limit-order", "trading", "buy", "sell"],
    hasPreview: true,
    importPath: "w3-kit/limit-order-manager",
    sourceUrl: `${GITHUB_BASE}/limit-order-manager`,
    props: [
      { name: "orders", type: "LimitOrder[]", required: true, description: "Order list (id, type buy/sell, token, amount, price, status, timestamp)" },
      { name: "onCancel", type: "(orderId: string) => void", required: false, description: "Called when user cancels an active order" },
      { name: "onCreateOrder", type: "() => void", required: false, description: "Called when user clicks New Order (parent handles form)" },
      { name: "cancellingId", type: "string", required: false, description: "Order ID being cancelled (shows loading spinner)" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "liquidity-pool-stats",
    name: "Liquidity Pool Stats",
    description: "Clean pool stats card with TVL, volume, APR, fees, transactions, holders, and action buttons.",
    category: "defi",
    tags: ["liquidity", "pool", "tvl", "volume", "apr"],
    hasPreview: true,
    importPath: "w3-kit/liquidity-pool-stats",
    sourceUrl: `${GITHUB_BASE}/liquidity-pool-stats`,
    props: [
      { name: "pool", type: "PoolStats", required: true, description: "Pool statistics — tokenPair, fee, tvl, volume24h, apr, and optional change/count fields" },
      { name: "onAddLiquidity", type: "() => void", required: false, description: "Callback when Add Liquidity is clicked" },
      { name: "onRemoveLiquidity", type: "() => void", required: false, description: "Callback when Remove Liquidity is clicked" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },

  // ── NFT ─────────────────────────────────────────────────
  {
    id: "nft-card",
    name: "NFT Card",
    description: "Display card for an NFT with image, attributes, owner, and collection info.",
    category: "nft",
    tags: ["nft", "collectible", "card"],
    hasPreview: false,
    importPath: "w3-kit/nft-card",
    sourceUrl: `${GITHUB_BASE}/nft-card`,
    props: [
      { name: "nft", type: "NFT", required: true, description: "NFT data object" },
      { name: "onNFTClick", type: "(nft: NFT) => void", required: false, description: "Callback when the card is clicked" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "nft-collection-grid",
    name: "NFT Collection Grid",
    description: "Responsive grid layout for displaying an NFT collection with header and count.",
    category: "nft",
    tags: ["nft", "collection", "grid", "gallery"],
    hasPreview: false,
    importPath: "w3-kit/nft-collection-grid",
    sourceUrl: `${GITHUB_BASE}/nft-collection-grid`,
    props: [
      { name: "nfts", type: "NFT[]", required: true, description: "Array of NFTs to display" },
      { name: "collectionName", type: "string", required: false, description: "Collection name for the header" },
      { name: "onNFTClick", type: "(nft: NFT) => void", required: false, description: "Callback when an NFT card is clicked" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "nft-marketplace-aggregator",
    name: "NFT Marketplace Aggregator",
    description:
      "Aggregated NFT listings from multiple marketplaces with best-price badges and verified status.",
    category: "nft",
    tags: ["marketplace", "opensea", "aggregator", "listing"],
    hasPreview: false,
    importPath: "w3-kit/nft-marketplace-aggregator",
    sourceUrl: `${GITHUB_BASE}/nft-marketplace-aggregator`,
    props: [
      { name: "initialListings", type: "NFTListing[]", required: false, description: "Initial listing data" },
      { name: "onBuy", type: "(listing: NFTListing) => void", required: false, description: "Callback when buying a listing" },
      { name: "loadingListingId", type: "string", required: false, description: "Listing ID currently loading" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },

  // ── Data ────────────────────────────────────────────────
  {
    id: "asset-portfolio",
    name: "Asset Portfolio",
    description:
      "Portfolio summary with allocation bar, sparklines, and cross-link hover effects.",
    category: "data",
    tags: ["portfolio", "allocation", "balance", "chart"],
    hasPreview: false,
    importPath: "w3-kit/asset-portfolio",
    sourceUrl: `${GITHUB_BASE}/asset-portfolio`,
    props: [
      { name: "assets", type: "Asset[]", required: true, description: "Portfolio asset list" },
      { name: "totalValue", type: "number", required: true, description: "Total portfolio value in USD" },
      { name: "totalChange24h", type: "number", required: true, description: "24h portfolio change percentage" },
      { name: "onAssetClick", type: "(asset: Asset) => void", required: false, description: "Callback when an asset is clicked" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "price-ticker",
    name: "Price Ticker",
    description: "Sortable token price table with market cap, volume, and trend indicators.",
    category: "data",
    tags: ["price", "ticker", "market", "table"],
    hasPreview: false,
    importPath: "w3-kit/price-ticker",
    sourceUrl: `${GITHUB_BASE}/price-ticker`,
    props: [
      { name: "tokens", type: "Token[]", required: true, description: "Token data to display" },
      { name: "onTokenClick", type: "(token: Token) => void", required: false, description: "Callback when a row is clicked" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "token-card",
    name: "Token Card",
    description: "Individual token display card with price, balance, and 24h change badge.",
    category: "data",
    tags: ["token", "card", "price"],
    hasPreview: false,
    importPath: "w3-kit/token-card",
    sourceUrl: `${GITHUB_BASE}/token-card`,
    props: [
      { name: "token", type: "Token", required: true, description: "Token data object" },
      { name: "onClick", type: "(token: Token) => void", required: false, description: "Callback when the card is clicked" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "token-list",
    name: "Token List",
    description: "Responsive token table with balance and value columns.",
    category: "data",
    tags: ["token", "list", "table"],
    hasPreview: false,
    importPath: "w3-kit/token-list",
    sourceUrl: `${GITHUB_BASE}/token-list`,
    props: [
      { name: "tokens", type: "Token[]", required: true, description: "Tokens to display" },
      { name: "onTokenSelect", type: "(token: Token) => void", required: false, description: "Callback when a token is selected" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "transaction-history",
    name: "Transaction History",
    description:
      "Transaction list with type icons, status indicators, and pending/failed counters.",
    category: "data",
    tags: ["transaction", "history", "activity"],
    hasPreview: false,
    importPath: "w3-kit/transaction-history",
    sourceUrl: `${GITHUB_BASE}/transaction-history`,
    props: [
      { name: "transactions", type: "Transaction[]", required: true, description: "Transaction data" },
      { name: "onTransactionClick", type: "(tx: Transaction) => void", required: false, description: "Callback when a transaction is clicked" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },

  // ── Utility ─────────────────────────────────────────────
  {
    id: "smart-contract-scanner",
    name: "Smart Contract Scanner",
    description:
      "Security scanner with address validation, scoring, individual checks, and source viewer.",
    category: "utility",
    tags: ["security", "audit", "scanner", "contract"],
    hasPreview: true,
    importPath: "w3-kit/smart-contract-scanner",
    sourceUrl: `${GITHUB_BASE}/smart-contract-scanner`,
    props: [
      { name: "onScan", type: "(address: string) => void", required: false, description: "Callback when scan is triggered" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "contract-interaction",
    name: "Contract Interaction",
    description: "Read/write smart contract functions with dynamic inputs and result history.",
    category: "utility",
    tags: ["contract", "abi", "read", "write"],
    hasPreview: false,
    importPath: "w3-kit/contract-interaction",
    sourceUrl: `${GITHUB_BASE}/contract-interaction`,
    props: [
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
      { name: "contractAddress", type: "string", required: false, description: "Pre-filled contract address" },
      { name: "functions", type: "ContractFunction[]", required: false, description: "Contract function definitions" },
      { name: "onExecute", type: "(name: string, inputs: string[]) => Promise<string>", required: false, description: "Callback to execute a function" },
    ],
  },
  {
    id: "ens-resolver",
    name: "ENS Resolver",
    description: "Resolve ENS names to addresses and vice-versa with avatar display.",
    category: "utility",
    tags: ["ens", "domain", "resolver"],
    hasPreview: false,
    importPath: "w3-kit/ens-resolver",
    sourceUrl: `${GITHUB_BASE}/ens-resolver`,
    props: [
      { name: "onResolve", type: "(result: ENSResult) => void", required: false, description: "Callback with resolution result" },
      { name: "resolver", type: "(input: string) => Promise<ENSResult>", required: false, description: "Custom resolver function" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "gas-calculator",
    name: "Gas Calculator",
    description: "Gas estimation tool with speed presets, transaction types, and USD costs.",
    category: "utility",
    tags: ["gas", "fee", "estimate", "gwei"],
    hasPreview: false,
    importPath: "w3-kit/gas-calculator",
    sourceUrl: `${GITHUB_BASE}/gas-calculator`,
    props: [
      { name: "onGasSelect", type: "(gas: number, price: number) => void", required: false, description: "Callback when a gas option is selected" },
      { name: "chainId", type: "number", required: false, description: "Chain ID for gas data" },
      { name: "ethPrice", type: "number", required: false, description: "Current ETH price in USD" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "subscription-payments",
    name: "Subscription Payments",
    description: "Crypto subscription plans with feature lists and pricing tiers.",
    category: "utility",
    tags: ["subscription", "payments", "plans", "pricing"],
    hasPreview: false,
    importPath: "w3-kit/subscription-payments",
    sourceUrl: `${GITHUB_BASE}/subscription-payments`,
    props: [
      { name: "plans", type: "SubscriptionPlan[]", required: true, description: "Available subscription plans" },
      { name: "onSubscribe", type: "(planId: string) => void", required: false, description: "Callback when subscribing" },
      { name: "loadingPlanId", type: "string", required: false, description: "Plan ID currently loading" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "token-airdrop",
    name: "Token Airdrop",
    description: "Airdrop claim interface with status badges, dates, and merkle proof verification.",
    category: "utility",
    tags: ["airdrop", "claim", "merkle"],
    hasPreview: false,
    importPath: "w3-kit/token-airdrop",
    sourceUrl: `${GITHUB_BASE}/token-airdrop`,
    props: [
      { name: "airdrops", type: "AirdropInfo[]", required: true, description: "List of available airdrops" },
      { name: "onClaim", type: "(airdropId: string) => Promise<void>", required: true, description: "Callback to claim an airdrop" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "token-vesting",
    name: "Token Vesting",
    description: "Vesting schedule display with progress bars, cliff dates, and claim buttons.",
    category: "utility",
    tags: ["vesting", "unlock", "schedule", "cliff"],
    hasPreview: false,
    importPath: "w3-kit/token-vesting",
    sourceUrl: `${GITHUB_BASE}/token-vesting`,
    props: [
      { name: "vestingSchedules", type: "VestingSchedule[]", required: true, description: "Vesting schedule data" },
      { name: "onClaimTokens", type: "(scheduleId: string) => Promise<void>", required: true, description: "Callback to claim vested tokens" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
];

export const primitivesRegistry = [
  { id: "button", name: "Button", description: "Flexible button with multiple variants and sizes." },
  { id: "badge", name: "Badge", description: "Small inline badge for status indicators." },
  { id: "card", name: "Card", description: "Composable card layout with header, content, and footer." },
  { id: "dialog", name: "Dialog", description: "Accessible modal dialog built on Radix UI." },
  { id: "input", name: "Input", description: "Styled text input with focus states." },
  { id: "progress", name: "Progress", description: "Progress bar indicator with smooth animations." },
  { id: "select", name: "Select", description: "Accessible dropdown select component." },
  { id: "stat", name: "Stat", description: "Statistic display with label and value." },
  { id: "status-dot", name: "Status Dot", description: "Colored dot for success, pending, or error." },
  { id: "tabs", name: "Tabs", description: "Tab navigation with content panels." },
  { id: "textarea", name: "Textarea", description: "Styled textarea input element." },
  { id: "token-icon", name: "Token Icon", description: "Token logo with fallback to symbol abbreviation." },
];
