import type { ComponentMeta } from "./types";

const GITHUB_BASE = "https://github.com/w3-kit/w3-kit/tree/main/ui/components";

export const componentRegistry: ComponentMeta[] = [
  // ── Wallet ──────────────────────────────────────────────
  {
    id: "connect-wallet",
    name: "Connect Wallet",
    description:
      "Multi-wallet connection button supporting MetaMask, WalletConnect, Coinbase, and Phantom.",
    category: "wallet",
    tags: ["metamask", "walletconnect", "coinbase", "phantom"],
    hasPreview: true,
    importPath: "w3-kit/connect-wallet",
    sourceUrl: `${GITHUB_BASE}/connect-wallet`,
    props: [
      { name: "onConnect", type: "(address: string) => void", required: false, description: "Callback when wallet connects successfully" },
      { name: "onError", type: "(error: Error) => void", required: false, description: "Callback when connection fails" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
      { name: "customLabel", type: "string", required: false, description: "Custom button label text" },
      { name: "variant", type: '"ghost" | "light" | "dark"', required: false, default: '"light"', description: "Visual style variant" },
      { name: "walletType", type: '"metamask" | "walletconnect" | "coinbase" | "phantom"', required: false, description: "Pre-select a specific wallet" },
    ],
  },
  {
    id: "network-switcher",
    name: "Network Switcher",
    description: "Chain selector with mainnet/testnet toggle and network metadata display.",
    category: "wallet",
    tags: ["chain", "network", "switch"],
    hasPreview: true,
    importPath: "w3-kit/network-switcher",
    sourceUrl: `${GITHUB_BASE}/network-switcher`,
    props: [
      { name: "networks", type: "Network[]", required: true, description: "List of available networks" },
      { name: "testNetworks", type: "Network[]", required: false, description: "Optional list of test networks" },
      { name: "onSwitch", type: "(chainId: number) => void", required: true, description: "Callback when user selects a network" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "wallet-balance",
    name: "Wallet Balance",
    description:
      "Token balance overview with total value, allocation bar, and 24h change indicators.",
    category: "wallet",
    tags: ["balance", "portfolio", "tokens"],
    hasPreview: true,
    importPath: "w3-kit/wallet-balance",
    sourceUrl: `${GITHUB_BASE}/wallet-balance`,
    props: [
      { name: "tokens", type: "Token[]", required: true, description: "List of tokens with balances" },
      { name: "onTokenClick", type: "(token: Token) => void", required: false, description: "Callback when a token row is clicked" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "address-book",
    name: "Address Book",
    description: "Manage saved addresses with ENS name support, notes, and CRUD operations.",
    category: "wallet",
    tags: ["address", "ens", "contacts"],
    hasPreview: false,
    importPath: "w3-kit/address-book",
    sourceUrl: `${GITHUB_BASE}/address-book`,
    props: [
      { name: "entries", type: "AddressEntry[]", required: true, description: "List of saved address entries" },
      { name: "onAdd", type: "(entry: Omit<AddressEntry, 'id'>) => void", required: false, description: "Callback when adding a new entry" },
      { name: "onEdit", type: "(entry: AddressEntry) => void", required: false, description: "Callback when editing an entry" },
      { name: "onDelete", type: "(id: string) => void", required: false, description: "Callback when deleting an entry" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "multisig-wallet",
    name: "Multisig Wallet",
    description:
      "Multi-signature wallet interface with signer management and transaction approval flow.",
    category: "wallet",
    tags: ["multisig", "gnosis", "safe", "approval"],
    hasPreview: false,
    importPath: "w3-kit/multisig-wallet",
    sourceUrl: `${GITHUB_BASE}/multisig-wallet`,
    props: [
      { name: "walletAddress", type: "string", required: true, description: "The multisig wallet address" },
      { name: "signers", type: "Signer[]", required: true, description: "List of wallet signers" },
      { name: "transactions", type: "Transaction[]", required: true, description: "Pending and past transactions" },
      { name: "requiredApprovals", type: "number", required: true, description: "Number of required approvals" },
      { name: "onApprove", type: "(txId: string) => void", required: false, description: "Callback when approving a transaction" },
      { name: "onReject", type: "(txId: string) => void", required: false, description: "Callback when rejecting a transaction" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },

  // ── DeFi ────────────────────────────────────────────────
  {
    id: "token-swap",
    name: "Token Swap",
    description: "Swap widget with token selectors, exchange rates, slippage settings, and USD estimates.",
    category: "defi",
    tags: ["swap", "dex", "exchange", "uniswap"],
    hasPreview: true,
    importPath: "w3-kit/token-swap",
    sourceUrl: `${GITHUB_BASE}/token-swap`,
    props: [
      { name: "onSwap", type: "(from: string, to: string, amount: string) => Promise<void>", required: true, description: "Callback to execute the swap" },
      { name: "tokens", type: "Token[]", required: false, description: "Available tokens for swapping" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "staking-interface",
    name: "Staking Interface",
    description:
      "Staking pool list with expandable details, stake/unstake toggle, and APR display.",
    category: "defi",
    tags: ["staking", "yield", "apr", "pool"],
    hasPreview: false,
    importPath: "w3-kit/staking-interface",
    sourceUrl: `${GITHUB_BASE}/staking-interface`,
    props: [
      { name: "pools", type: "StakingPool[]", required: true, description: "Available staking pools" },
      { name: "onStake", type: "(poolId: string, amount: string) => void", required: false, description: "Callback when staking" },
      { name: "onUnstake", type: "(poolId: string, amount: string) => void", required: false, description: "Callback when unstaking" },
      { name: "loadingPoolId", type: "string", required: false, description: "Pool ID currently loading" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "bridge",
    name: "Bridge Widget",
    description: "Cross-chain bridge interface with network and token selection.",
    category: "defi",
    tags: ["bridge", "cross-chain", "transfer"],
    hasPreview: false,
    importPath: "w3-kit/bridge",
    sourceUrl: `${GITHUB_BASE}/bridge`,
    props: [
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
      { name: "networks", type: "Network[]", required: false, description: "Available networks" },
      { name: "tokens", type: "BridgeToken[]", required: false, description: "Available tokens" },
      { name: "onBridge", type: "(params) => void | Promise<void>", required: false, description: "Callback to execute the bridge" },
    ],
  },
  {
    id: "defi-position-manager",
    name: "DeFi Position Manager",
    description:
      "Dashboard for open DeFi positions showing health factor, APY, rewards, and risk level.",
    category: "defi",
    tags: ["position", "health", "apy", "rewards"],
    hasPreview: false,
    importPath: "w3-kit/defi-position-manager",
    sourceUrl: `${GITHUB_BASE}/defi-position-manager`,
    props: [
      { name: "positions", type: "PositionData[]", required: true, description: "Active DeFi positions" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "flash-loan-executor",
    name: "Flash Loan Executor",
    description: "Execute flash loans with protocol and token selection.",
    category: "defi",
    tags: ["flash-loan", "aave", "arbitrage"],
    hasPreview: false,
    importPath: "w3-kit/flash-loan-executor",
    sourceUrl: `${GITHUB_BASE}/flash-loan-executor`,
    props: [
      { name: "protocols", type: "Protocol[]", required: true, description: "Available flash loan protocols" },
      { name: "tokens", type: "FlashLoanToken[]", required: true, description: "Available tokens" },
      { name: "onExecute", type: "(protocol: string, token: string, amount: string) => void | Promise<void>", required: false, description: "Callback to execute the flash loan" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "limit-order-manager",
    name: "Limit Order Manager",
    description: "Manage limit and stop-loss orders with status tracking and cancellation.",
    category: "defi",
    tags: ["limit-order", "stop-loss", "trading"],
    hasPreview: false,
    importPath: "w3-kit/limit-order-manager",
    sourceUrl: `${GITHUB_BASE}/limit-order-manager`,
    props: [
      { name: "orders", type: "OrderData[]", required: true, description: "List of orders" },
      { name: "onOrderCreate", type: "(order) => void", required: false, description: "Callback when creating an order" },
      { name: "onOrderCancel", type: "(orderId: string) => void", required: false, description: "Callback when cancelling an order" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "liquidity-pool-stats",
    name: "Liquidity Pool Stats",
    description: "Pool statistics dashboard with TVL, volume, APR, fees, and holder metrics.",
    category: "defi",
    tags: ["liquidity", "pool", "tvl", "volume"],
    hasPreview: false,
    importPath: "w3-kit/liquidity-pool-stats",
    sourceUrl: `${GITHUB_BASE}/liquidity-pool-stats`,
    props: [
      { name: "poolData", type: "PoolData", required: true, description: "Pool statistics data" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },

  // ── NFT ─────────────────────────────────────────────────
  {
    id: "nft-card",
    name: "NFT Card",
    description: "Display card for an NFT with image, attributes, owner, and collection info.",
    category: "nft",
    tags: ["nft", "collectible", "card"],
    hasPreview: false,
    importPath: "w3-kit/nft-card",
    sourceUrl: `${GITHUB_BASE}/nft-card`,
    props: [
      { name: "nft", type: "NFT", required: true, description: "NFT data object" },
      { name: "onNFTClick", type: "(nft: NFT) => void", required: false, description: "Callback when the card is clicked" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "nft-collection-grid",
    name: "NFT Collection Grid",
    description: "Responsive grid layout for displaying an NFT collection with header and count.",
    category: "nft",
    tags: ["nft", "collection", "grid", "gallery"],
    hasPreview: false,
    importPath: "w3-kit/nft-collection-grid",
    sourceUrl: `${GITHUB_BASE}/nft-collection-grid`,
    props: [
      { name: "nfts", type: "NFT[]", required: true, description: "Array of NFTs to display" },
      { name: "collectionName", type: "string", required: false, description: "Collection name for the header" },
      { name: "onNFTClick", type: "(nft: NFT) => void", required: false, description: "Callback when an NFT card is clicked" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "nft-marketplace-aggregator",
    name: "NFT Marketplace Aggregator",
    description:
      "Aggregated NFT listings from multiple marketplaces with best-price badges and verified status.",
    category: "nft",
    tags: ["marketplace", "opensea", "aggregator", "listing"],
    hasPreview: false,
    importPath: "w3-kit/nft-marketplace-aggregator",
    sourceUrl: `${GITHUB_BASE}/nft-marketplace-aggregator`,
    props: [
      { name: "initialListings", type: "NFTListing[]", required: false, description: "Initial listing data" },
      { name: "onBuy", type: "(listing: NFTListing) => void", required: false, description: "Callback when buying a listing" },
      { name: "loadingListingId", type: "string", required: false, description: "Listing ID currently loading" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },

  // ── Data ────────────────────────────────────────────────
  {
    id: "asset-portfolio",
    name: "Asset Portfolio",
    description:
      "Portfolio summary with allocation bar, sparklines, and cross-link hover effects.",
    category: "data",
    tags: ["portfolio", "allocation", "balance", "chart"],
    hasPreview: false,
    importPath: "w3-kit/asset-portfolio",
    sourceUrl: `${GITHUB_BASE}/asset-portfolio`,
    props: [
      { name: "assets", type: "Asset[]", required: true, description: "Portfolio asset list" },
      { name: "totalValue", type: "number", required: true, description: "Total portfolio value in USD" },
      { name: "totalChange24h", type: "number", required: true, description: "24h portfolio change percentage" },
      { name: "onAssetClick", type: "(asset: Asset) => void", required: false, description: "Callback when an asset is clicked" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "price-ticker",
    name: "Price Ticker",
    description: "Sortable token price table with market cap, volume, and trend indicators.",
    category: "data",
    tags: ["price", "ticker", "market", "table"],
    hasPreview: false,
    importPath: "w3-kit/price-ticker",
    sourceUrl: `${GITHUB_BASE}/price-ticker`,
    props: [
      { name: "tokens", type: "Token[]", required: true, description: "Token data to display" },
      { name: "onTokenClick", type: "(token: Token) => void", required: false, description: "Callback when a row is clicked" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "token-card",
    name: "Token Card",
    description: "Individual token display card with price, balance, and 24h change badge.",
    category: "data",
    tags: ["token", "card", "price"],
    hasPreview: false,
    importPath: "w3-kit/token-card",
    sourceUrl: `${GITHUB_BASE}/token-card`,
    props: [
      { name: "token", type: "Token", required: true, description: "Token data object" },
      { name: "onClick", type: "(token: Token) => void", required: false, description: "Callback when the card is clicked" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "token-list",
    name: "Token List",
    description: "Responsive token table with balance and value columns.",
    category: "data",
    tags: ["token", "list", "table"],
    hasPreview: false,
    importPath: "w3-kit/token-list",
    sourceUrl: `${GITHUB_BASE}/token-list`,
    props: [
      { name: "tokens", type: "Token[]", required: true, description: "Tokens to display" },
      { name: "onTokenSelect", type: "(token: Token) => void", required: false, description: "Callback when a token is selected" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "transaction-history",
    name: "Transaction History",
    description:
      "Transaction list with type icons, status indicators, and pending/failed counters.",
    category: "data",
    tags: ["transaction", "history", "activity"],
    hasPreview: false,
    importPath: "w3-kit/transaction-history",
    sourceUrl: `${GITHUB_BASE}/transaction-history`,
    props: [
      { name: "transactions", type: "Transaction[]", required: true, description: "Transaction data" },
      { name: "onTransactionClick", type: "(tx: Transaction) => void", required: false, description: "Callback when a transaction is clicked" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },

  // ── Utility ─────────────────────────────────────────────
  {
    id: "smart-contract-scanner",
    name: "Smart Contract Scanner",
    description:
      "Security scanner with address validation, scoring, individual checks, and source viewer.",
    category: "utility",
    tags: ["security", "audit", "scanner", "contract"],
    hasPreview: true,
    importPath: "w3-kit/smart-contract-scanner",
    sourceUrl: `${GITHUB_BASE}/smart-contract-scanner`,
    props: [
      { name: "onScan", type: "(address: string) => void", required: false, description: "Callback when scan is triggered" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "contract-interaction",
    name: "Contract Interaction",
    description: "Read/write smart contract functions with dynamic inputs and result history.",
    category: "utility",
    tags: ["contract", "abi", "read", "write"],
    hasPreview: false,
    importPath: "w3-kit/contract-interaction",
    sourceUrl: `${GITHUB_BASE}/contract-interaction`,
    props: [
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
      { name: "contractAddress", type: "string", required: false, description: "Pre-filled contract address" },
      { name: "functions", type: "ContractFunction[]", required: false, description: "Contract function definitions" },
      { name: "onExecute", type: "(name: string, inputs: string[]) => Promise<string>", required: false, description: "Callback to execute a function" },
    ],
  },
  {
    id: "ens-resolver",
    name: "ENS Resolver",
    description: "Resolve ENS names to addresses and vice-versa with avatar display.",
    category: "utility",
    tags: ["ens", "domain", "resolver"],
    hasPreview: false,
    importPath: "w3-kit/ens-resolver",
    sourceUrl: `${GITHUB_BASE}/ens-resolver`,
    props: [
      { name: "onResolve", type: "(result: ENSResult) => void", required: false, description: "Callback with resolution result" },
      { name: "resolver", type: "(input: string) => Promise<ENSResult>", required: false, description: "Custom resolver function" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "gas-calculator",
    name: "Gas Calculator",
    description: "Gas estimation tool with speed presets, transaction types, and USD costs.",
    category: "utility",
    tags: ["gas", "fee", "estimate", "gwei"],
    hasPreview: false,
    importPath: "w3-kit/gas-calculator",
    sourceUrl: `${GITHUB_BASE}/gas-calculator`,
    props: [
      { name: "onGasSelect", type: "(gas: number, price: number) => void", required: false, description: "Callback when a gas option is selected" },
      { name: "chainId", type: "number", required: false, description: "Chain ID for gas data" },
      { name: "ethPrice", type: "number", required: false, description: "Current ETH price in USD" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "subscription-payments",
    name: "Subscription Payments",
    description: "Crypto subscription plans with feature lists and pricing tiers.",
    category: "utility",
    tags: ["subscription", "payments", "plans", "pricing"],
    hasPreview: false,
    importPath: "w3-kit/subscription-payments",
    sourceUrl: `${GITHUB_BASE}/subscription-payments`,
    props: [
      { name: "plans", type: "SubscriptionPlan[]", required: true, description: "Available subscription plans" },
      { name: "onSubscribe", type: "(planId: string) => void", required: false, description: "Callback when subscribing" },
      { name: "loadingPlanId", type: "string", required: false, description: "Plan ID currently loading" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "token-airdrop",
    name: "Token Airdrop",
    description: "Airdrop claim interface with status badges, dates, and merkle proof verification.",
    category: "utility",
    tags: ["airdrop", "claim", "merkle"],
    hasPreview: false,
    importPath: "w3-kit/token-airdrop",
    sourceUrl: `${GITHUB_BASE}/token-airdrop`,
    props: [
      { name: "airdrops", type: "AirdropInfo[]", required: true, description: "List of available airdrops" },
      { name: "onClaim", type: "(airdropId: string) => Promise<void>", required: true, description: "Callback to claim an airdrop" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
  {
    id: "token-vesting",
    name: "Token Vesting",
    description: "Vesting schedule display with progress bars, cliff dates, and claim buttons.",
    category: "utility",
    tags: ["vesting", "unlock", "schedule", "cliff"],
    hasPreview: false,
    importPath: "w3-kit/token-vesting",
    sourceUrl: `${GITHUB_BASE}/token-vesting`,
    props: [
      { name: "vestingSchedules", type: "VestingSchedule[]", required: true, description: "Vesting schedule data" },
      { name: "onClaimTokens", type: "(scheduleId: string) => Promise<void>", required: true, description: "Callback to claim vested tokens" },
      { name: "className", type: "string", required: false, description: "Additional CSS classes" },
    ],
  },
];

export const primitivesRegistry = [
  { id: "button", name: "Button", description: "Flexible button with multiple variants and sizes." },
  { id: "badge", name: "Badge", description: "Small inline badge for status indicators." },
  { id: "card", name: "Card", description: "Composable card layout with header, content, and footer." },
  { id: "dialog", name: "Dialog", description: "Accessible modal dialog built on Radix UI." },
  { id: "input", name: "Input", description: "Styled text input with focus states." },
  { id: "progress", name: "Progress", description: "Progress bar indicator with smooth animations." },
  { id: "select", name: "Select", description: "Accessible dropdown select component." },
  { id: "stat", name: "Stat", description: "Statistic display with label and value." },
  { id: "status-dot", name: "Status Dot", description: "Colored dot for success, pending, or error." },
  { id: "tabs", name: "Tabs", description: "Tab navigation with content panels." },
  { id: "textarea", name: "Textarea", description: "Styled textarea input element." },
  { id: "token-icon", name: "Token Icon", description: "Token logo with fallback to symbol abbreviation." },
];
