// AUTO-GENERATED by scripts/generate-learn-registry.ts — do not edit manually
import type { RecipeMeta } from "./types";

import approveSpendingMeta from "@learn/recipes/approve-spending/meta.json";
import approveSpendingEvm from "@learn/recipes/approve-spending/evm.tsx?raw";
import approveSpendingSolana from "@learn/recipes/approve-spending/solana.tsx?raw";
import approveSpendingLearn from "@learn/recipes/approve-spending/approve-spending.learn.md?raw";
import buyNftMeta from "@learn/recipes/buy-nft/meta.json";
import buyNftEvm from "@learn/recipes/buy-nft/evm.tsx?raw";
import buyNftSolana from "@learn/recipes/buy-nft/solana.tsx?raw";
import buyNftLearn from "@learn/recipes/buy-nft/buy-nft.learn.md?raw";
import claimRewardsMeta from "@learn/recipes/claim-rewards/meta.json";
import claimRewardsEvm from "@learn/recipes/claim-rewards/evm.tsx?raw";
import claimRewardsSolana from "@learn/recipes/claim-rewards/solana.tsx?raw";
import claimRewardsLearn from "@learn/recipes/claim-rewards/claim-rewards.learn.md?raw";
import connectWalletMeta from "@learn/recipes/connect-wallet/meta.json";
import connectWalletEvm from "@learn/recipes/connect-wallet/evm.tsx?raw";
import connectWalletSolana from "@learn/recipes/connect-wallet/solana.tsx?raw";
import connectWalletLearn from "@learn/recipes/connect-wallet/connect-wallet.learn.md?raw";
import createTokenMeta from "@learn/recipes/create-token/meta.json";
import createTokenEvm from "@learn/recipes/create-token/evm.tsx?raw";
import createTokenSolana from "@learn/recipes/create-token/solana.tsx?raw";
import createTokenLearn from "@learn/recipes/create-token/create-token.learn.md?raw";
import disconnectWalletMeta from "@learn/recipes/disconnect-wallet/meta.json";
import disconnectWalletEvm from "@learn/recipes/disconnect-wallet/evm.tsx?raw";
import disconnectWalletSolana from "@learn/recipes/disconnect-wallet/solana.tsx?raw";
import disconnectWalletLearn from "@learn/recipes/disconnect-wallet/disconnect-wallet.learn.md?raw";
import displayNftMetadataMeta from "@learn/recipes/display-nft-metadata/meta.json";
import displayNftMetadataEvm from "@learn/recipes/display-nft-metadata/evm.tsx?raw";
import displayNftMetadataSolana from "@learn/recipes/display-nft-metadata/solana.tsx?raw";
import displayNftMetadataLearn from "@learn/recipes/display-nft-metadata/display-nft-metadata.learn.md?raw";
import estimateFeesMeta from "@learn/recipes/estimate-fees/meta.json";
import estimateFeesEvm from "@learn/recipes/estimate-fees/evm.tsx?raw";
import estimateFeesSolana from "@learn/recipes/estimate-fees/solana.tsx?raw";
import estimateFeesLearn from "@learn/recipes/estimate-fees/estimate-fees.learn.md?raw";
import fetchMetadataMeta from "@learn/recipes/fetch-metadata/meta.json";
import fetchMetadataEvm from "@learn/recipes/fetch-metadata/evm.tsx?raw";
import fetchMetadataSolana from "@learn/recipes/fetch-metadata/solana.tsx?raw";
import fetchMetadataLearn from "@learn/recipes/fetch-metadata/fetch-metadata.learn.md?raw";
import fetchNftCollectionMeta from "@learn/recipes/fetch-nft-collection/meta.json";
import fetchNftCollectionEvm from "@learn/recipes/fetch-nft-collection/evm.tsx?raw";
import fetchNftCollectionSolana from "@learn/recipes/fetch-nft-collection/solana.tsx?raw";
import fetchNftCollectionLearn from "@learn/recipes/fetch-nft-collection/fetch-nft-collection.learn.md?raw";
import getBalanceMeta from "@learn/recipes/get-balance/meta.json";
import getBalanceEvm from "@learn/recipes/get-balance/evm.tsx?raw";
import getBalanceSolana from "@learn/recipes/get-balance/solana.tsx?raw";
import getBalanceLearn from "@learn/recipes/get-balance/get-balance.learn.md?raw";
import mintNftMeta from "@learn/recipes/mint-nft/meta.json";
import mintNftEvm from "@learn/recipes/mint-nft/evm.tsx?raw";
import mintNftSolana from "@learn/recipes/mint-nft/solana.tsx?raw";
import mintNftLearn from "@learn/recipes/mint-nft/mint-nft.learn.md?raw";
import onchainSvgNftMeta from "@learn/recipes/onchain-svg-nft/meta.json";
import onchainSvgNftEvm from "@learn/recipes/onchain-svg-nft/evm.tsx?raw";
import onchainSvgNftLearn from "@learn/recipes/onchain-svg-nft/onchain-svg-nft.learn.md?raw";
import provideLiquidityMeta from "@learn/recipes/provide-liquidity/meta.json";
import provideLiquidityEvm from "@learn/recipes/provide-liquidity/evm.tsx?raw";
import provideLiquiditySolana from "@learn/recipes/provide-liquidity/solana.tsx?raw";
import provideLiquidityLearn from "@learn/recipes/provide-liquidity/provide-liquidity.learn.md?raw";
import resolveAddressMeta from "@learn/recipes/resolve-address/meta.json";
import resolveAddressEvm from "@learn/recipes/resolve-address/evm.tsx?raw";
import resolveAddressSolana from "@learn/recipes/resolve-address/solana.tsx?raw";
import resolveAddressLearn from "@learn/recipes/resolve-address/resolve-address.learn.md?raw";
import signMessageMeta from "@learn/recipes/sign-message/meta.json";
import signMessageEvm from "@learn/recipes/sign-message/evm.tsx?raw";
import signMessageSolana from "@learn/recipes/sign-message/solana.tsx?raw";
import signMessageLearn from "@learn/recipes/sign-message/sign-message.learn.md?raw";
import stakeTokensMeta from "@learn/recipes/stake-tokens/meta.json";
import stakeTokensEvm from "@learn/recipes/stake-tokens/evm.tsx?raw";
import stakeTokensSolana from "@learn/recipes/stake-tokens/solana.tsx?raw";
import stakeTokensLearn from "@learn/recipes/stake-tokens/stake-tokens.learn.md?raw";
import swapTokensMeta from "@learn/recipes/swap-tokens/meta.json";
import swapTokensEvm from "@learn/recipes/swap-tokens/evm.tsx?raw";
import swapTokensSolana from "@learn/recipes/swap-tokens/solana.tsx?raw";
import swapTokensLearn from "@learn/recipes/swap-tokens/swap-tokens.learn.md?raw";
import switchNetworkMeta from "@learn/recipes/switch-network/meta.json";
import switchNetworkEvm from "@learn/recipes/switch-network/evm.tsx?raw";
import switchNetworkSolana from "@learn/recipes/switch-network/solana.tsx?raw";
import switchNetworkLearn from "@learn/recipes/switch-network/switch-network.learn.md?raw";
import transferTokensMeta from "@learn/recipes/transfer-tokens/meta.json";
import transferTokensEvm from "@learn/recipes/transfer-tokens/evm.tsx?raw";
import transferTokensSolana from "@learn/recipes/transfer-tokens/solana.tsx?raw";
import transferTokensLearn from "@learn/recipes/transfer-tokens/transfer-tokens.learn.md?raw";
import watchTransfersMeta from "@learn/recipes/watch-transfers/meta.json";
import watchTransfersEvm from "@learn/recipes/watch-transfers/evm.tsx?raw";
import watchTransfersSolana from "@learn/recipes/watch-transfers/solana.tsx?raw";
import watchTransfersLearn from "@learn/recipes/watch-transfers/watch-transfers.learn.md?raw";

export const recipeRegistry: RecipeMeta[] = [
  {
    id: approveSpendingMeta.name,
    name: approveSpendingMeta.name,
    description: approveSpendingMeta.description,
    slug: approveSpendingMeta.name,
    chains: approveSpendingMeta.chains,
    dependencies: approveSpendingMeta.dependencies,
    evmCode: approveSpendingEvm,
    solanaCode: approveSpendingSolana,
    learnContent: approveSpendingLearn,
    author: approveSpendingMeta.author ?? "",
  },
  {
    id: buyNftMeta.name,
    name: buyNftMeta.name,
    description: buyNftMeta.description,
    slug: buyNftMeta.name,
    chains: buyNftMeta.chains,
    dependencies: buyNftMeta.dependencies,
    evmCode: buyNftEvm,
    solanaCode: buyNftSolana,
    learnContent: buyNftLearn,
    author: buyNftMeta.author ?? "",
  },
  {
    id: claimRewardsMeta.name,
    name: claimRewardsMeta.name,
    description: claimRewardsMeta.description,
    slug: claimRewardsMeta.name,
    chains: claimRewardsMeta.chains,
    dependencies: claimRewardsMeta.dependencies,
    evmCode: claimRewardsEvm,
    solanaCode: claimRewardsSolana,
    learnContent: claimRewardsLearn,
    author: claimRewardsMeta.author ?? "",
  },
  {
    id: connectWalletMeta.name,
    name: connectWalletMeta.name,
    description: connectWalletMeta.description,
    slug: connectWalletMeta.name,
    chains: connectWalletMeta.chains,
    dependencies: connectWalletMeta.dependencies,
    evmCode: connectWalletEvm,
    solanaCode: connectWalletSolana,
    learnContent: connectWalletLearn,
    author: connectWalletMeta.author ?? "",
  },
  {
    id: createTokenMeta.name,
    name: createTokenMeta.name,
    description: createTokenMeta.description,
    slug: createTokenMeta.name,
    chains: createTokenMeta.chains,
    dependencies: createTokenMeta.dependencies,
    evmCode: createTokenEvm,
    solanaCode: createTokenSolana,
    learnContent: createTokenLearn,
    author: createTokenMeta.author ?? "",
  },
  {
    id: disconnectWalletMeta.name,
    name: disconnectWalletMeta.name,
    description: disconnectWalletMeta.description,
    slug: disconnectWalletMeta.name,
    chains: disconnectWalletMeta.chains,
    dependencies: disconnectWalletMeta.dependencies,
    evmCode: disconnectWalletEvm,
    solanaCode: disconnectWalletSolana,
    learnContent: disconnectWalletLearn,
    author: disconnectWalletMeta.author ?? "",
  },
  {
    id: displayNftMetadataMeta.name,
    name: displayNftMetadataMeta.name,
    description: displayNftMetadataMeta.description,
    slug: displayNftMetadataMeta.name,
    chains: displayNftMetadataMeta.chains,
    dependencies: displayNftMetadataMeta.dependencies,
    evmCode: displayNftMetadataEvm,
    solanaCode: displayNftMetadataSolana,
    learnContent: displayNftMetadataLearn,
    author: displayNftMetadataMeta.author ?? "",
  },
  {
    id: estimateFeesMeta.name,
    name: estimateFeesMeta.name,
    description: estimateFeesMeta.description,
    slug: estimateFeesMeta.name,
    chains: estimateFeesMeta.chains,
    dependencies: estimateFeesMeta.dependencies,
    evmCode: estimateFeesEvm,
    solanaCode: estimateFeesSolana,
    learnContent: estimateFeesLearn,
    author: estimateFeesMeta.author ?? "",
  },
  {
    id: fetchMetadataMeta.name,
    name: fetchMetadataMeta.name,
    description: fetchMetadataMeta.description,
    slug: fetchMetadataMeta.name,
    chains: fetchMetadataMeta.chains,
    dependencies: fetchMetadataMeta.dependencies,
    evmCode: fetchMetadataEvm,
    solanaCode: fetchMetadataSolana,
    learnContent: fetchMetadataLearn,
    author: fetchMetadataMeta.author ?? "",
  },
  {
    id: fetchNftCollectionMeta.name,
    name: fetchNftCollectionMeta.name,
    description: fetchNftCollectionMeta.description,
    slug: fetchNftCollectionMeta.name,
    chains: fetchNftCollectionMeta.chains,
    dependencies: fetchNftCollectionMeta.dependencies,
    evmCode: fetchNftCollectionEvm,
    solanaCode: fetchNftCollectionSolana,
    learnContent: fetchNftCollectionLearn,
    author: fetchNftCollectionMeta.author ?? "",
  },
  {
    id: getBalanceMeta.name,
    name: getBalanceMeta.name,
    description: getBalanceMeta.description,
    slug: getBalanceMeta.name,
    chains: getBalanceMeta.chains,
    dependencies: getBalanceMeta.dependencies,
    evmCode: getBalanceEvm,
    solanaCode: getBalanceSolana,
    learnContent: getBalanceLearn,
    author: getBalanceMeta.author ?? "",
  },
  {
    id: mintNftMeta.name,
    name: mintNftMeta.name,
    description: mintNftMeta.description,
    slug: mintNftMeta.name,
    chains: mintNftMeta.chains,
    dependencies: mintNftMeta.dependencies,
    evmCode: mintNftEvm,
    solanaCode: mintNftSolana,
    learnContent: mintNftLearn,
    author: mintNftMeta.author ?? "",
  },
  {
    id: onchainSvgNftMeta.name,
    name: onchainSvgNftMeta.name,
    description: onchainSvgNftMeta.description,
    slug: onchainSvgNftMeta.name,
    chains: onchainSvgNftMeta.chains,
    dependencies: onchainSvgNftMeta.dependencies,
    evmCode: onchainSvgNftEvm,
    solanaCode: "",
    learnContent: onchainSvgNftLearn,
    author: onchainSvgNftMeta.author ?? "",
  },
  {
    id: provideLiquidityMeta.name,
    name: provideLiquidityMeta.name,
    description: provideLiquidityMeta.description,
    slug: provideLiquidityMeta.name,
    chains: provideLiquidityMeta.chains,
    dependencies: provideLiquidityMeta.dependencies,
    evmCode: provideLiquidityEvm,
    solanaCode: provideLiquiditySolana,
    learnContent: provideLiquidityLearn,
    author: provideLiquidityMeta.author ?? "",
  },
  {
    id: resolveAddressMeta.name,
    name: resolveAddressMeta.name,
    description: resolveAddressMeta.description,
    slug: resolveAddressMeta.name,
    chains: resolveAddressMeta.chains,
    dependencies: resolveAddressMeta.dependencies,
    evmCode: resolveAddressEvm,
    solanaCode: resolveAddressSolana,
    learnContent: resolveAddressLearn,
    author: resolveAddressMeta.author ?? "",
  },
  {
    id: signMessageMeta.name,
    name: signMessageMeta.name,
    description: signMessageMeta.description,
    slug: signMessageMeta.name,
    chains: signMessageMeta.chains,
    dependencies: signMessageMeta.dependencies,
    evmCode: signMessageEvm,
    solanaCode: signMessageSolana,
    learnContent: signMessageLearn,
    author: signMessageMeta.author ?? "",
  },
  {
    id: stakeTokensMeta.name,
    name: stakeTokensMeta.name,
    description: stakeTokensMeta.description,
    slug: stakeTokensMeta.name,
    chains: stakeTokensMeta.chains,
    dependencies: stakeTokensMeta.dependencies,
    evmCode: stakeTokensEvm,
    solanaCode: stakeTokensSolana,
    learnContent: stakeTokensLearn,
    author: stakeTokensMeta.author ?? "",
  },
  {
    id: swapTokensMeta.name,
    name: swapTokensMeta.name,
    description: swapTokensMeta.description,
    slug: swapTokensMeta.name,
    chains: swapTokensMeta.chains,
    dependencies: swapTokensMeta.dependencies,
    evmCode: swapTokensEvm,
    solanaCode: swapTokensSolana,
    learnContent: swapTokensLearn,
    author: swapTokensMeta.author ?? "",
  },
  {
    id: switchNetworkMeta.name,
    name: switchNetworkMeta.name,
    description: switchNetworkMeta.description,
    slug: switchNetworkMeta.name,
    chains: switchNetworkMeta.chains,
    dependencies: switchNetworkMeta.dependencies,
    evmCode: switchNetworkEvm,
    solanaCode: switchNetworkSolana,
    learnContent: switchNetworkLearn,
    author: switchNetworkMeta.author ?? "",
  },
  {
    id: transferTokensMeta.name,
    name: transferTokensMeta.name,
    description: transferTokensMeta.description,
    slug: transferTokensMeta.name,
    chains: transferTokensMeta.chains,
    dependencies: transferTokensMeta.dependencies,
    evmCode: transferTokensEvm,
    solanaCode: transferTokensSolana,
    learnContent: transferTokensLearn,
    author: transferTokensMeta.author ?? "",
  },
  {
    id: watchTransfersMeta.name,
    name: watchTransfersMeta.name,
    description: watchTransfersMeta.description,
    slug: watchTransfersMeta.name,
    chains: watchTransfersMeta.chains,
    dependencies: watchTransfersMeta.dependencies,
    evmCode: watchTransfersEvm,
    solanaCode: watchTransfersSolana,
    learnContent: watchTransfersLearn,
    author: watchTransfersMeta.author ?? "",
  },
];
