/**
 * Auto-fetch script for landing page stats.
 *
 * Pulls live numbers at build time:
 *   - GitHub stars across the w3-kit org
 *   - npm weekly downloads summed across published packages
 *   - Component count from ui/registry/w3-kit/
 *   - Chain count from registry/data/chains.json
 *
 * Falls back to safe defaults if a request fails so dev/build keeps working
 * offline. Writes to src/entities/stats/model/stats.gen.ts.
 *
 * Run: npx tsx scripts/generate-stats.ts
 * Wired into: "prebuild" and "predev" npm scripts (via "generate")
 */

import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "../..");
const UI_REGISTRY_DIR = path.join(ROOT, "ui/registry/w3-kit");
const CHAINS_JSON = path.join(ROOT, "registry/data/chains.json");

const OUT_FILE = path.resolve(
  import.meta.dirname,
  "../src/entities/stats/model/stats.gen.ts",
);

// ── Sources ─────────────────────────────────────────────────────────────────

// Repos under the w3-kit org we want to sum stars across.
const GH_REPOS = [
  "w3-kit/website",
  "w3-kit/ui",
  "w3-kit/cli",
  "w3-kit/registry",
  "w3-kit/learn",
  "w3-kit/contracts",
  "w3-kit/config",
  "w3-kit/bot",
];

// Published npm packages we want to sum weekly downloads across.
const NPM_PACKAGES = [
  "w3-kit",
  "@w3-kit/registry",
  "@w3-kit/config",
  "@w3-kit/mcp",
];

// ── Helpers ─────────────────────────────────────────────────────────────────

function fmtCompact(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1).replace(/\.0$/, "")}M`;
  if (n >= 10_000) return `${Math.round(n / 1_000)}k`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1).replace(/\.0$/, "")}k`;
  return String(n);
}

async function fetchJson<T>(url: string, headers: Record<string, string> = {}): Promise<T | null> {
  try {
    const res = await fetch(url, {
      headers: { "User-Agent": "w3-kit-website-stats", ...headers },
    });
    if (!res.ok) return null;
    return (await res.json()) as T;
  } catch {
    return null;
  }
}

// ── Fetchers ────────────────────────────────────────────────────────────────

async function fetchGithubStars(): Promise<number> {
  const headers: Record<string, string> = {};
  const token = process.env.GITHUB_TOKEN;
  if (token) headers.Authorization = `Bearer ${token}`;

  const results = await Promise.all(
    GH_REPOS.map(async (repo) => {
      const data = await fetchJson<{ stargazers_count?: number }>(
        `https://api.github.com/repos/${repo}`,
        headers,
      );
      return data?.stargazers_count ?? 0;
    }),
  );
  return results.reduce((a, b) => a + b, 0);
}

async function fetchNpmWeeklyDownloads(): Promise<number> {
  const results = await Promise.all(
    NPM_PACKAGES.map(async (pkg) => {
      const data = await fetchJson<{ downloads?: number }>(
        `https://api.npmjs.org/downloads/point/last-week/${encodeURIComponent(pkg)}`,
      );
      return data?.downloads ?? 0;
    }),
  );
  return results.reduce((a, b) => a + b, 0);
}

function countComponents(): number {
  if (!fs.existsSync(UI_REGISTRY_DIR)) return 0;
  return fs
    .readdirSync(UI_REGISTRY_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory()).length;
}

function countChains(): number {
  if (!fs.existsSync(CHAINS_JSON)) return 0;
  try {
    const data = JSON.parse(fs.readFileSync(CHAINS_JSON, "utf-8"));
    return Array.isArray(data) ? data.length : Object.keys(data).length;
  } catch {
    return 0;
  }
}

// ── Run ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log("Fetching landing stats...");

  const [stars, npmWeekly] = await Promise.all([
    fetchGithubStars(),
    fetchNpmWeeklyDownloads(),
  ]);
  const components = countComponents();
  const chains = countChains();

  console.log(`  GitHub stars (org sum): ${stars}`);
  console.log(`  npm downloads / week:   ${npmWeekly}`);
  console.log(`  Components:             ${components}`);
  console.log(`  Chains:                 ${chains}`);

  const generatedAt = new Date().toISOString();

  const content = `/* AUTO-GENERATED by scripts/generate-stats.ts — do not edit by hand. */

export interface LandingStat {
  big: string;
  sml: string;
  sub: string;
}

export const STATS_GENERATED_AT = "${generatedAt}";

export const LANDING_STATS: LandingStat[] = [
  {
    big: ${JSON.stringify(stars > 0 ? fmtCompact(stars) : "—")},
    sml: "GitHub stars",
    sub: "across the w3-kit org",
  },
  {
    big: ${JSON.stringify(npmWeekly > 0 ? fmtCompact(npmWeekly) : "—")},
    sml: "npm downloads / week",
    sub: "across @w3-kit/*",
  },
  {
    big: ${JSON.stringify(String(components))},
    sml: "components shipped",
    sub: "typed, themed, ready",
  },
  {
    big: ${JSON.stringify(String(chains))},
    sml: "chains supported",
    sub: "EVM + Solana",
  },
];
`;

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, content);
  console.log(`  Wrote ${path.relative(path.resolve(import.meta.dirname, ".."), OUT_FILE)}`);
  console.log("Done!");
}

main().catch((err) => {
  console.error("generate-stats failed:", err);
  process.exit(0); // never fail the build over a stats fetch
});
