/**
 * Auto-discovery script for blog posts in content/blog/.
 *
 * Walks every *.md file, parses YAML frontmatter manually (no new deps),
 * sorts by date desc, and writes src/entities/blog-post/model/posts.gen.ts.
 *
 * Run: npx tsx scripts/generate-blog-registry.ts
 * Wired into: "generate" npm script (predev + prebuild)
 */

import fs from "node:fs";
import path from "node:path";

const WEBSITE_ROOT = path.resolve(import.meta.dirname, "..");
const CONTENT_DIR = path.join(WEBSITE_ROOT, "content/blog");
const OUT_PATH = path.join(WEBSITE_ROOT, "src/entities/blog-post/model/posts.gen.ts");

type Frontmatter = {
  title: string;
  date: string;
  kind: "post" | "changelog";
  summary: string;
  tags: string[];
};

function parseFrontmatter(raw: string): { fm: Frontmatter; body: string } {
  const match = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) {
    throw new Error("missing or malformed frontmatter");
  }
  const [, yamlBlock, body] = match;

  const fm: Partial<Frontmatter> = { tags: [] };
  const lines = yamlBlock.split("\n");
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    if (!line.trim()) {
      i++;
      continue;
    }
    const inlineTags = line.match(/^tags:\s*\[(.*)\]\s*$/);
    if (inlineTags) {
      fm.tags = inlineTags[1]
        .split(",")
        .map((t) => t.trim().replace(/^["']|["']$/g, ""))
        .filter(Boolean);
      i++;
      continue;
    }
    if (line.match(/^tags:\s*$/)) {
      i++;
      const tags: string[] = [];
      while (i < lines.length && /^\s+-\s+/.test(lines[i])) {
        tags.push(lines[i].replace(/^\s+-\s+/, "").trim().replace(/^["']|["']$/g, ""));
        i++;
      }
      fm.tags = tags;
      continue;
    }
    const kv = line.match(/^(\w+):\s*(.*)$/);
    if (kv) {
      const key = kv[1];
      let value = kv[2].trim();
      if (
        (value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))
      ) {
        value = value.slice(1, -1);
      }
      (fm as Record<string, unknown>)[key] = value;
    }
    i++;
  }

  if (!fm.title || !fm.date || !fm.kind || !fm.summary) {
    throw new Error(`missing required frontmatter fields: ${JSON.stringify(fm)}`);
  }

  return { fm: fm as Frontmatter, body: body.replace(/^\n+/, "") };
}

function deriveSlug(filename: string): string {
  const base = filename.replace(/\.md$/, "");
  return base.replace(/^\d{4}-\d{2}-\d{2}-/, "");
}

function main() {
  if (!fs.existsSync(CONTENT_DIR)) {
    fs.mkdirSync(CONTENT_DIR, { recursive: true });
  }

  const files = fs.readdirSync(CONTENT_DIR).filter((f) => f.endsWith(".md"));
  const posts = files
    .map((file) => {
      const raw = fs.readFileSync(path.join(CONTENT_DIR, file), "utf8");
      const { fm, body } = parseFrontmatter(raw);
      return {
        slug: deriveSlug(file),
        title: fm.title,
        date: fm.date,
        kind: fm.kind,
        summary: fm.summary,
        tags: fm.tags ?? [],
        content: body,
      };
    })
    .sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0));

  const header = `// Generated by scripts/generate-blog-registry.ts — do not edit\n`;
  const importLine = `import type { BlogPost } from "./types";\n\n`;
  const body = `export const POSTS: BlogPost[] = ${JSON.stringify(posts, null, 2)};\n`;

  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, header + importLine + body);
  console.log(`  wrote ${path.relative(WEBSITE_ROOT, OUT_PATH)} (${posts.length} posts)`);
}

main();
