/**
 * Reads chains.json / tokens.json / solana-programs.json from either the
 * sibling registry repo or a shallow clone, and writes typed registries
 * into src/entities/*\/model/*.gen.ts.
 *
 * Pattern mirrors scripts/generate-stats.ts.
 *
 * Run: npx tsx scripts/generate-registry-data.ts
 * Wired into: "generate" npm script (which runs in "predev" and "prebuild")
 */

import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";

const WEBSITE_ROOT = path.resolve(import.meta.dirname, "..");
const ROOT = path.resolve(WEBSITE_ROOT, "..");

const REGISTRY_CLONE = path.join(WEBSITE_ROOT, ".tmp-registry-mirror");
const REGISTRY_REPO_URL = "https://github.com/w3-kit/registry.git";

function resolveDataDir(): string {
  const sibling = path.join(ROOT, "registry/data");
  if (fs.existsSync(sibling)) return sibling;

  const cloned = path.join(REGISTRY_CLONE, "data");
  if (fs.existsSync(cloned)) return cloned;

  console.log(`  registry sibling not found, cloning ${REGISTRY_REPO_URL}`);
  execSync(`git clone --depth 1 --quiet ${REGISTRY_REPO_URL} "${REGISTRY_CLONE}"`, {
    stdio: ["ignore", "ignore", "inherit"],
  });
  return cloned;
}

function readJson<T>(dir: string, file: string): T {
  const full = path.join(dir, file);
  const raw = fs.readFileSync(full, "utf8");
  return JSON.parse(raw) as T;
}

function writeRegistry(
  targetPath: string,
  constName: string,
  typeName: string,
  importFrom: string,
  data: unknown,
) {
  const header = `// Generated by scripts/generate-registry-data.ts — do not edit\n`;
  const importLine = `import type { ${typeName} } from "${importFrom}";\n\n`;
  const body = `export const ${constName}: ${typeName}[] = ${JSON.stringify(data, null, 2)};\n`;
  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  fs.writeFileSync(targetPath, header + importLine + body);
  console.log(
    `  wrote ${path.relative(WEBSITE_ROOT, targetPath)} (${(data as unknown[]).length} entries)`,
  );
}

function main() {
  const dataDir = resolveDataDir();

  const chains = readJson<unknown[]>(dataDir, "chains.json");
  const tokens = readJson<unknown[]>(dataDir, "tokens.json");
  const programs = readJson<unknown[]>(dataDir, "solana-programs.json");

  writeRegistry(
    path.join(WEBSITE_ROOT, "src/entities/chain/model/chains.gen.ts"),
    "CHAINS",
    "Chain",
    "./types",
    chains,
  );
  writeRegistry(
    path.join(WEBSITE_ROOT, "src/entities/token/model/tokens.gen.ts"),
    "TOKENS",
    "Token",
    "./types",
    tokens,
  );
  writeRegistry(
    path.join(WEBSITE_ROOT, "src/entities/program/model/programs.gen.ts"),
    "PROGRAMS",
    "SolanaProgram",
    "./types",
    programs,
  );

  console.log("  registry data generated");
}

main();
